command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]

env:
  - name: CATALOG_NAME
    value: "lr_dev_aws_us_catalog"
  - name: SCHEMA_NAME
    value: "underwriting_workbench"
  - name: WAREHOUSE_ID
    valueFrom: sql_warehouse
  - name: USE_CACHE
    value: "true"
  - name: FM_ENDPOINT
    value: "databricks-claude-sonnet-4-5"
  - name: GENIE_SPACE_ID
    value: "01f17afafb6d1309bcff27506395be54"
  - name: DASHBOARD_ID
    value: "01f17afbb9bc192f993f9a26d2343bdb"
  - name: CLAIMS_APP_URL
    value: "https://claims-workbench-7474656169654171.aws.databricksapps.com"
